spring:
  application:
    server-port: 8080
    name: saude-praja-api
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/saudepraja
    username: root
    password: 1937852
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  version: '@springdoc.version@'
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        security: DEBUG

saudepraja.auth.provider-url: "http://localhost:8080"